### ISSUE TITLE
To-do list editing experience is atrocious

### ISSUE THREAD

**Issue by koraa** [streetwriters/notesnook#1363]
### What happened?

I moved to notesnook from my personal hedgedoc instance.

Unfortunately, to-do list editing experience was drastically reduced. In hedgedoc I could always copy/paste or move around todos by just copying the `* [x]` / `* [ ]` code.

In notesnook I can not do that because there is no way to select the check box itself. I have to select the text and move it around, thereby loosing the information which was checked.

In hedgedoc I can copy things into my text editor and past without loosing any information; in notesnook I can not copy that. Pretty much all features used by hedgedoc are supported by markdown; my suggestion is to copy paste as richt text where possible adding in markdown where applicable.

I suggest to also add an option to copy/paste strictly as markdown.

Please make sure there are clear rules when lists are merged; I often end up with empty lines when deleting points or merged lists where I do not want to merge them.

---

To provide a real, tangible improvement over a self-hosted hedgedoc instace when it comes to  todo-list keeping I suggest adding dedicated todo-list features, such as:

* [ ] automatically tagging todo list points with date of creation/date of completion
* [ ] Creating todos from a central location; e.g. typing `todo:work Do the thing` might create a todo in the work note reading "Do the thing"` without adding the note.
* [ ] Display aggregated todos; e.g. unified view for "work" and "chores" todo lists
* [ ] Automatic sorting
* [ ] Due date support
* [ ] Infinite todo lists (hide points completed after a while)

### Steps to reproduce the problem

--

### Version

latest

### Platform/OS

Windows, macOS, Linux, iOS, Android, Chrome/Chromium, Firefox, Safari, Other browser

**Comment by koraa** [comment]
Hi Abdullah,

thank you for responding so quickly! I hope my frustration does not swap over too much; I moved my sizeable stack of notes to notesnook a couple of months ago only to find out I have to spend three times as much on notes handling just from editor clumsiness.

I haven't spend the full effort that would be required to UX-test and describe these issues fully because that involves a lot of effort; I am in a high-stress phase right now and can not spend the time unfortunately, I hope the hints are still useful to you; if any particular point is very confusing, I am happy to go back and elaborate on that particular point.

> Have you tried using the drag/drop feature with the to-do list items?

Yes, I do use the drag and drop feature; on browser it works ok-ish, still feels a bit clumsy and sometimes drag and drop does not work and I have to retry. On mobile, I can not reach the small point matrix with my fingers; I use a heavy duty phone case that makes it hard to input events at the very border of the screen. How about making the entire width of the note area for drag and drop; maybe with a long-hold?

The main concern is that I am trying to edit many todos at once; my workflow involves checking off a couple to-dos and then moving it to an archival todo list; moving all the todos one by one would be extremely tedious.

I am also a heavy keyboard user, so I'd rather use a keyboard based workflow if at all possible.
 
> I'll see if it is possible to include checked/unchecked information when copying.
> 
> I will take a look at the other suggestions and reply accordingly.

Thank you!
